### ISSUE TITLE
windows CI

### ISSUE THREAD

**Issue by stefanpenner** [shinnn/broccoli-clean-css#10]
https://ci.appveyor.com/project/ShinnosukeWatanabe/broccoli-clean-css

i dont believe explicit paths will work in windows: https://github.com/shinnn/broccoli-clean-css/blob/master/package.json#L11 `node_modules/.bin/istanbul` maybe there is a trick?

A quick fix, would be to disable coverage for windows, and let the posix suite handle that.

**Comment by stefanpenner** [comment]
Let me know if ^ works for you, I can gladly doit just give me a +1

**Comment by shinnn** [comment]
I just disabled coverage checking on AppVeyor, and it passes the test now.
