### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by g13013** [shinnn/broccoli-clean-css#11]
Hi there

You broke the hole world with this commit https://github.com/shinnn/broccoli-clean-css/commit/9e560a54e83760658a4b1d9645112871062f0349

I get `ReferenceError: Promise is not defined` on  new builds using version `@1.1.0`, with the version `@1.0.0`, all was fine

since we reference `^1.0.0` in our `packages.json`, new build started to fails since you released `1.1.0`
it is always a best practice to raise the major version of the module if it introduces breaking changes

info
node version: `v0.10.30`

**Comment by shinnn** [comment]
Thanks for the report. Fixed in [clean-css-promise](https://github.com/shinnn/clean-css-promise) [v0.1.1](https://github.com/shinnn/clean-css-promise/commit/373e0b095b12a11043701b2e8bb0e202e1cc3427).

Reinstall `broccoli-clean-css` and you can get the Node 0.10 compatible version.

**Comment by g13013** [comment]
Thank you for you quick fix :+1:
