### ISSUE TITLE
Provide a way to not use the source directory for `relativeTo`

### ISSUE THREAD

**Issue by XrXr** [shinnn/broccoli-clean-css#12]
@shinnn In old versions of `broccoli-clean-css` `relativeTo` can be set to anything. However in newer versions it is always relative to the source directory.

Libraries that use the old behaviour are blocked from upgrading because of this (ember-cli/ember-cli-preprocessor-registry#6)

Can we get some way to bypass this [forced rebasing](https://github.com/shinnn/broccoli-clean-css/blob/master/index.js#L49)?

**Comment by rwjblue** [comment]
I believe that the behavior of `relativeTo` in broccoli-clean-css is correct even though it was a breaking change to ember-cli (which was absolutely fine to do in a major version bump). See my detailed explanation in https://github.com/ember-cli/ember-cli-preprocessor-registry/issues/6#issuecomment-183884529.

ember-cli is being updated to use the correct value for `relativeTo` in https://github.com/ember-cli/ember-cli/pull/5463.

**Comment by XrXr** [comment]
Cool! There is no problem then.
