### ISSUE TITLE
Should rebase default to false?

### ISSUE THREAD

**Issue by joliss** [shinnn/broccoli-clean-css#18]
I realize you may be hesitant to override defaults provided by the clean-css upstream, but I'm wondering if it would actually make sense for this plugin to default the [`rebase` option](https://github.com/jakubpawlowicz/clean-css#constructor-options) to `false`.

I ran the following code in my `Brocfile.js`, expecting that minifying the CSS would preserve its semantics:

```js
if (production) {
  outputNode = new BroccoliCleanCss(outputNode);
}
```

This almost worked, except that clean-css rewrote all image references in `styles/foo.css` as if they were relative to the `outputNode` root rather than the `styles/` directory.

I'm not entirely sure why clean-css defaults its `rebase` feature to `true`, but perhaps it might make sense for this plugin to default it to `false`?

I'm happy to submit a pull request if you think that this is a reasonable change.

This change would probably warrant a version bump to 3.0.0, since it breaks the default behavior.

**Comment by shinnn** [comment]
What really causes this problem is not `rebase` option but the default `rebaseTo` option value of this plugin:

> `rebaseTo` option is regarded as relative to the Broccoli target path.

I'll get rid of this behavior in the next major version.
