### ISSUE TITLE
Support sourceMaps

### ISSUE THREAD

**Issue by naartjie** [shinnn/broccoli-clean-css#2]
`clean-css` has started implementing source maps on the [f/source-maps](https://github.com/jakubpawlowicz/clean-css/issues/125) branch. I think we should implement this in the plugin too.

I have already started some work on this, and I will update as soon as I have something that's useable.

**Comment by shinnn** [comment]
@naartjie Thank you very much for waiting so long! I released v1.0.0 which supports source map.
