### ISSUE TITLE
Update clean-css to 3.0

### ISSUE THREAD

**Issue by jakubpawlowicz** [shinnn/broccoli-clean-css#3]
It was released yesterday and here are upgrade instructions: https://github.com/jakubpawlowicz/clean-css#how-to-upgrade-clean-css-from-2x-to-3x

**Comment by shinnn** [comment]
@jakubpawlowicz Thank you very much for waiting so long! I released v1.0.0 which uses clean-css v3.x and supports source map.

**Comment by jakubpawlowicz** [comment]
Great! :100:
