### ISSUE TITLE
output file as XXXXX.min.css

### ISSUE THREAD

**Issue by smurgolo** [shinnn/broccoli-clean-css#5]
Hi!
Is there any explanation why you set the file extension only as css: https://github.com/shinnn/broccoli-clean-css/blob/master/index.js#L23 ?

I'm using this package with ember-cli and I'm trying to create the output file as name.min.css and with that restriction I couldn't. 

Did I miss anything?
Thanks!

**Comment by shinnn** [comment]
[broccoli-rename-files](https://github.com/zeppelin/broccoli-rename-files) (or something else) helps you.

**Comment by smurgolo** [comment]
Thank you for the quick reply!
